name: pysp2-docs
channels:
  - conda-forge
dependencies:
  - act-atmos
  - xarray
  - pandas
  - numpy
  - scipy
  - xlrd
  - matplotlib
  - sphinx
  - pydata-sphinx-theme
  - arm-test-data
  - pip:
      - sphinx_gallery
      - sphinx-copybutton
      - sphinx_design
      - nbsphinx
      - sphinxcontrib-applehelp<1.0.8
